#
# Copyright (c) 2024 The ZMK Contributors
# SPDX-License-Identifier: MIT
#
# Note: CONFIG_ZMK_SLEEP=y is inherited from the shared eyelash_corne.conf.

#EXT POWER
CONFIG_ZMK_EXT_POWER=y

#EC11 enable
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# === Studio (Central only) ===
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_BLE_MANAGEMENT=y
CONFIG_ZMK_BLE_MANAGEMENT_STUDIO_RPC=y

# === Runtime Input Processor (Central only) ===
CONFIG_ZMK_RUNTIME_INPUT_PROCESSOR=y
CONFIG_ZMK_RUNTIME_INPUT_PROCESSOR_STUDIO_RPC=y

# === Settings RPC (Central only) ===
CONFIG_ZMK_SETTINGS_RPC=y
CONFIG_ZMK_SETTINGS_RPC_STUDIO=y

# === Runtime Sensor Rotate (Encoder, Central only) ===
CONFIG_ZMK_RUNTIME_SENSOR_ROTATE=y
CONFIG_ZMK_RUNTIME_SENSOR_ROTATE_STUDIO_RPC=y

# === Settings (Central only) ===
CONFIG_SETTINGS=y

# === Battery (Central only) ===
CONFIG_ZMK_BATTERY_HISTORY=n
CONFIG_ZMK_BATTERY_HISTORY_STUDIO_RPC=n

# === Split (Central only) ===
CONFIG_ZMK_SPLIT_RELAY_EVENT=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_SPLIT_RUN_STACK_SIZE=1024
CONFIG_ZMK_SETTINGS_SAVE_DEBOUNCE=10000

# Display ON (central only)
CONFIG_ZMK_DISPLAY=y
