#
# Copyright (c) 2024 The ZMK Contributors
# SPDX-License-Identifier: MIT
#

#EXT POWER
CONFIG_ZMK_EXT_POWER=y

#EC11 enable
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# === Basic ===
CONFIG_INPUT=y

# === Battery (Peripheral) ===
CONFIG_ZMK_BATTERY_HISTORY=n
CONFIG_ZMK_BATTERY_HISTORY_INTERVAL_MINUTES=30
CONFIG_ZMK_SETTINGS_RPC=y
CONFIG_ZMK_SPLIT_RELAY_EVENT=y
CONFIG_ZMK_SETTINGS_SAVE_DEBOUNCE=10000

# Display OFF (peripheral screen blank)
CONFIG_ZMK_DISPLAY=n
